export const APPLICATION_SET_PROGRESS = 'APPLICATION_SET_PROGRESS';
export const APPLICATION_OPEN_CLOSE_DRAWER = 'APPLICATION_OPEN_CLOSE_DRAWER';
export const APPLICATION_SET_USER = 'APPLICATION_SET_USER';
export const APPLICATION_RESET_USER = 'APPLICATION_RESET_USER';
export const APPLICATION_SET_CARD_PIN = 'APPLICATION_SET_CARD_PIN';
export const APPLICATION_SET_ABOUT_SOFTWARE = 'APPLICATION_SET_ABOUT_SOFTWARE';
export const APPLICATION_OPEN_KEYBOARD_SIMULATION = 'APPLICATION_OPEN_KEYBOARD_SIMULATION';
export const APPLICATION_TOGGLE_KEYBOARD_SIMULATION = 'APPLICATION_TOGGLE_KEYBOARD_SIMULATION';
