export const ERROR_ARTICLE_PRICE_NOT_VALID = 'ARTICLE PRICE NOT VALID';
export const ERROR_ARTICLE_VAT_NOT_VALID = 'ARTICLE VAT NOT VALID';
export const ERROR_ARTICLE_DESC_NOT_VALID = 'ARTICLE DESCRIPTION NOT VALID';
export const ERROR_ARTICLE_BAR_CODE_NOT_VALID = 'ARTICLE BAR CODE NOT VALID';
export const ERROR_ARTICLE_MEASURE_NOT_VALID = 'ARTICLE MEASURE NOT VALID';

export const ERROR_USER_PIN_NOT_VALID = 'USER PIN NOT VALID';
export const ERROR_USER_PIN_ALREADY_USED = 'USER PIN ALREADY USED';

export const ERROR_LOCK_SCREEN_PIN_NOT_VALID = 'PIN NIJE ISPRAVAN';

export const ERROR_CLIENT_TIN_NOT_VALID = 'PIB NIJE DOBRE DUŽINE';
export const ERROR_CLIENT_TIN_ALREADY_USED = 'CLIENT PIB ALREADY USED';
