import {StyleSheet} from 'react-native';
import {Colors} from 'src/constants/Colors';

const style = StyleSheet.create({
  root: {
    flex: 1,
    height: '100%',
  },
  dailyReportBody: {
    flex: 2,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  dailyReportsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: 5,
    borderBottomWidth: 2,
    borderStyle: 'solid',
    borderColor: Colors.PALETTE.GRAY._500,
    backgroundColor: Colors.WHITE,
  },
  dailyReportsHeaderText: {
    fontSize: 17,
    color: Colors.PALETTE.GRAY._700,
    fontWeight: 'bold',
  },
  dateReportVatHeader: {
    flexDirection: 'row',
    backgroundColor: Colors.PALETTE.GRAY._300,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '5%',
    borderStyle: 'solid',
    borderTopWidth: 2,
    borderTopColor: Colors.PALETTE.GRAY._500,
    borderColor: Colors.PALETTE.GRAY._600,
  },
  dateReportVatHeaderType: {
    flex: 1,
    color: Colors.PALETTE.GRAY._800,
    fontSize: 17,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  dateReportVatHeaderTxt: {
    color: Colors.PALETTE.GRAY._800,
    fontSize: 17,
  },
  dateReportVatItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '4%',
    paddingVertical: 4,
    borderStyle: 'dashed',
    borderBottomWidth: 1,
    borderBottomColor: Colors.PALETTE.GRAY._500,
  },
  dateReportVatItemSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '4%',
    paddingVertical: 3,
    borderStyle: 'dashed',
    borderBottomWidth: 1,
    borderBottomColor: Colors.PALETTE.GRAY._500,
    backgroundColor: Colors.PALETTE.LIGHT_BLUE._50,
  },
  dateReportVatItemType: {
    color: Colors.PALETTE.GRAY._700,
    fontSize: 17,
  },
  dateReportSummaryText: {
    fontSize: 17,
    color: Colors.PALETTE.GRAY._600,
    fontWeight: 'bold',
  },
  dateReportVatItemTypeSummary: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.PALETTE.GRAY._600,
  },
  dateReportVatItemTxt: {
    color: Colors.PALETTE.GRAY._700,
    fontSize: 15,
    textAlign: 'right',
    flex: 1,
  },
  dateReportItem: {
    flexDirection: 'column',
  },
  dataReportTimeAndCounterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  nonReportContainer: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nonReportText: {
    color: Colors.PALETTE.GRAY._700,
  },
  dailyReportHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.PALETTE.GRAY._200,
    paddingVertical: 3,
    paddingHorizontal: '4%',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    borderColor: Colors.PALETTE.GRAY._500,
    width: '100%',
  },
  dailyReportCountersText: {
    flex: 1,
    fontSize: 17,
    color: Colors.PALETTE.GRAY._800,
    textAlign: 'right',
    fontWeight: 'bold',
  },
  dailyReportTotalCountersText: {
    flex: 1,
    fontSize: 18,
    color: Colors.PALETTE.GRAY._700,
    textAlign: 'left',
    fontWeight: '700',
  },
  dailyReportRightPartContainer: {
    flexDirection: 'row',
    flex: 2,
    justifyContent: 'space-between',
  },
  dailyReportLabelContainer: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-start',
  },
  dateReportPaymentItemTxt: {
    color: Colors.PALETTE.GRAY._700,
    fontSize: 15,
    textAlign: 'left',
    flex: 1,
  },
  dateReportInvoiceTypeItemHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: Colors.PALETTE.GRAY._50,
    paddingVertical: 0,
    paddingHorizontal: 10,
    width: '100%',
  },
  dateReportInvoiceTypeItemHeaderTxt: {
    fontSize: 12,
    fontWeight: 'bold',
    color: Colors.PALETTE.GRAY._700,
  },
  dailyReportInvoicePartHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.PALETTE.GRAY._100,
    paddingVertical: 4,
    paddingHorizontal: '4%',
    borderBottomWidth: 2,
    borderTopWidth: 1,
    borderStyle: 'solid',
    borderColor: Colors.PALETTE.GRAY._500,
    width: '100%',
  },
  dailyReportVatsTotalContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dateReportVatsTotalHelpText: {
    flex: 1,
    fontSize: 17,
    color: Colors.PALETTE.GRAY._600,
    fontWeight: 'bold',
  },
  dateReportVatsTotalText: {
    flex: 1,
    fontSize: 17,
    color: Colors.PALETTE.GRAY._600,
    fontWeight: '700',
    textAlign: 'right',
  },
  dateReportVatsTotalTaxText: {
    flex: 1,
    fontSize: 17,
    color: Colors.PALETTE.GRAY._600,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

export default style;
