import {StyleSheet} from 'react-native';
import {Colors} from 'src/constants/Colors';
import {transparentize} from 'polished';
import {Fonts} from '../../../constants/Constants';

const style = StyleSheet.create({
  root: {
    flex: 1,
    width: '100%',
    backgroundColor: Colors.WHITE,
    //borderRadius: 5,
    paddingVertical: 5,
    paddingLeft: 10,
    paddingRight: 5,
    shadowColor: Colors.PALETTE.GRAY._500,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    minHeight: 70,
    maxHeight: 70,
    borderBottomWidth: 1,
    borderBottomColor: Colors.PALETTE.GRAY._200,
    borderStyle: 'solid',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'stretch',
  },
  itemOdd: {
    backgroundColor: Colors.PALETTE.CYAN._50,
  },
  itemAdded: {
    backgroundColor: Colors.PALETTE.GREEN._50,
  },
  itemChangeQty: {
    backgroundColor: Colors.PALETTE.INDIGO._50,
  },
  flexRow: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  descriptionLabel: {
    flex: 2,
    fontSize: 18,
    lineHeight: 20,
    fontFamily: Fonts.CONDENSED,
    paddingLeft: 3,
    paddingTop: 2,
  },
  itemDiscount: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    flex: 1,
  },
  itemDiscountText: {
    fontSize: 15,
    lineHeight: 15,
    fontFamily: Fonts.CONDENSED,
    color: Colors.PALETTE.GRAY._600,
    textAlign: 'right',
  },
  itemDiscountView: {
    minWidth: 40,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  itemNumber: {
    fontSize: 15,
    lineHeight: 20,
    color: Colors.PALETTE.GRAY._600,
    fontFamily: Fonts.CONDENSED,
    marginRight: 5,
  },
  itemTaxContainer: {
    width: 23,
    height: 23,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 2,
  },
  itemTax: {
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 20,
    borderRadius: 200,
    padding: 1,
    textAlign: 'center',
    color: Colors.WHITE,
    fontFamily: Fonts.CONDENSED,
  },
  itemDescSecondLine: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  itemBarCode: {
    minWidth: 50,
    maxWidth: 50,
    overflow: 'hidden',
  },
  itemBarcodeText: {
    fontSize: 12,
    color: Colors.PALETTE.GRAY._500,
    fontFamily: Fonts.CONDENSED,
    textAlign: 'left',
  },
  itemCode: {
    fontSize: 9,
    color: Colors.PALETTE.GRAY._500,
    fontFamily: Fonts.CONDENSED,
  },
  itemQtyPriceContainer: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '100%',
  },
  itemPrice: {
    //minWidth: 70,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemPriceText: {
    fontWeight: '600',
    fontSize: 17,
    textAlign: 'center',
    fontFamily: Fonts.CONDENSED,
  },
  itemQty: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    textAlign: 'right',
    fontFamily: Fonts.CONDENSED,
    flex: 1,
  },
  itemQuantityMultiSign: {
    fontSize: 12,
    fontWeight: 'bold',
    paddingLeft: 5,
    fontFamily: Fonts.CONDENSED,
  },
  itemQtyText: {
    fontWeight: 'bold',
    fontSize: 17,
    minWidth: 10,
    textAlign: 'right',
    fontFamily: Fonts.CONDENSED,
  },
  itemTotalText: {
    fontWeight: 'bold',
    fontSize: 18,
    textAlign: 'right',
    fontFamily: Fonts.SPACE_MONO,
  },
  swipeRowBackRoot: {
    alignItems: 'center',
    backgroundColor: transparentize(0.2, Colors.PALETTE.GRAY._200),
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 5,
    flex: 1,
    width: '100%',
    height: 70,
  },
  swipeBackRightBtn: {
    overlayColor: transparentize(0.7, Colors.PALETTE.RED._800),
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    minWidth: 75,
    flex: 1,
    right: 0,
    backgroundColor: Colors.PALETTE.RED._800,
    color: Colors.WHITE,
  },
  swipeBackLeftBtn: {
    overlayColor: transparentize(0.7, Colors.PALETTE.BLUE._700),
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    backgroundColor: Colors.PALETTE.BLUE._700,
    minWidth: 75,
    height: 'auto',
    left: 0,
  },
  disabled: {
    opacity: 0.2,
    backgroundColor: transparentize(0.7, Colors.PALETTE.BLUE._700),
  },
  backTextWhite: {
    color: Colors.WHITE,
  },
  iconsView: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    fontSize: 26,
    color: Colors.WHITE,
  },
  iconPercentClear: {
    fontSize: 26,
    color: Colors.WHITE,
  },
  iconPercent: {
    position: 'absolute',
    top: 8,
    fontSize: 14,
    color: Colors.PALETTE.BLUE._700,
    zIndex: 10,
  },
  itemCell: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemTotal: {
    minWidth: 70,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  itemDiscountContainer: {
    flex: 1.5,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
  },
  itemDiscountRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  itemDiscountRowBorder: {
    flex: 1,
    flexDirection: 'row',
    borderStyle: 'solid',
    borderBottomColor: Colors.PALETTE.GRAY._600,
    borderBottomWidth: 1,
    paddingBottom: 1,
  },
  itemDiscountHelpText: {
    fontWeight: '600',
    fontSize: 12,
    fontFamily: Fonts.CONDENSED,
  },
  itemDiscountPrice: {
    minWidth: 70,
    fontWeight: '600',
    fontSize: 16,
    textAlign: 'center',
    fontFamily: Fonts.CONDENSED,
    flex: 2,
  },
});

export default style;
