export const LPFR_PIN_VERIFIED = 'LPFR_PIN_VERIFIED'
export const LPFR_CLEAR_ALL = 'LPFR_CLAER_ALL'
export const LPFR_SET_STATUS_INFO = 'LPFR_SET_INFO_STATE'
export const LPFR_SET_IS_ALIVE = 'LPFR_SET_IS_ALIVE_FLAG'
export const LPFR_SET_STATUS_PAYER = 'LPFR_SET_STATUS_PAYER'
export const LPFR_SET_STATUS_CRITIC_ERROR = 'LPFR_SET_STATUS_CRITIC_ERROR'
export const LPFR_SET_STATUS_SETTINGS = 'LPFR_SET_STATUS_SETTINGS'
export const LPFR_SET_STATUS_BASIC = 'LPFR_SET_STATUS_BASIC'
export const LPFR_SET_IS_PIN_VERIFIED = 'LPFR_IS_PIN_VERIFIED'

export const LPFR_SET_ENVIRONMENT = 'LPFR_SET_ENVIRONMENT'

export const LPFR_SET_THROW_ERROR = 'LPFR_SET_THROW_ERROR'
export const LPFR_SET_THROW_ERROR_CLEAR = 'LPFR_SET_THROW_ERROR_CLEAR'

