import {StyleSheet} from 'react-native';
import {Colors} from 'src/constants/Colors';
import {Fonts} from '../../constants/Constants';

const style = StyleSheet.create({
  root: {
    flex: 1,
    paddingVertical: 10,
  },
  header: {
    height: 48,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
    borderBottomWidth: 2,
    borderStyle: 'solid',
    borderColor: Colors.PALETTE.GRAY._400,
    zIndex: 2,
    position: 'relative',
  },
  receiptCollapsibleContainer: {
    position: 'absolute',
    top: 55,
    width: '100%',
    zIndex: 1,
  },
  receiptTypeContainer: {
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  receiptTypeLabel: {
    fontSize: 9,
    fontWeight: 'normal',
    opacity: 0.7,
    marginBottom: 5,
  },
  receiptTypeTextContainer: {
    flex: 2,
    width: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  receiptTypeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  totalContainer: {
    flex: 1,
    height: '100%',
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: 'stretch',
    justifyContent: 'center',
  },
  receiptSummaryTitle: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  receiptSummaryFinance: {
    flex: 2,
    width: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  receiptTotalFinanceText: {
    width: '100%',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'right',
    fontFamily: Fonts.CONDENSED,
  },
  receiptSummaryTotalText: {
    fontWeight: '700',
    fontSize: 13,
  },
  receiptSummaryTapToPayText: {
    fontWeight: 'normal',
    opacity: 0.7,
    fontSize: 10,
  },
  body: {
    flex: 2,
    height: '100%',
    width: '100%',
    position: "relative"
  },
  receiptFooterContainer: {
    flexDirection: 'row',
    height: 50,
    borderStyle: 'solid',
    borderTopWidth: 2,
    borderTopColor: Colors.PALETTE.GRAY._400,
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: '100%',
    zIndex: 2,
    backgroundColor: Colors.WHITE,
  },
  receiptFooterTypeContainer: {
    flex: 1,
    paddingVertical: 5,
    borderStyle: 'solid',
    borderRightWidth: 1,
    borderRightColor: Colors.PALETTE.GRAY._400,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  receiptFooterIcon: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptFooterTypeInfoContainer: {
    paddingHorizontal: 5,
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  receiptFooterRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  receiptFooterHeaderTypeText: {
    fontSize: 8,
    fontWeight: 'normal',
    color: Colors.PALETTE.GRAY._500,
    flex: 2,
  },
  receiptFooterRefundNumberText: {
    fontSize: 8,
    color: Colors.PALETTE.GRAY._500,
  },
  receiptFooterType: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptFooterTypeText: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.PALETTE.GRAY._950,
  },
  receiptTotalContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 10,
    position: 'relative',
    height: '100%',
  },
  receiptTotalIcon: {
    position: 'absolute',
    bottom: 5,
    left: 10,
    opacity: 0.5,
  },
  receiptFooterTypeIcon: {
    color: Colors.PALETTE.BLUE._700,
    fontSize: 20,
    opacity: 0.4,
    position: 'absolute',
    right: 5,
    bottom: 5,
  },
  receiptFooterSelect: {
    flex: 1,
    width: 235,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: Colors.PALETTE.GRAY._400,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    maxHeight: 45,
    padding: 5,
    margin: 5,
    borderRadius: 10,
    backgroundColor: Colors.PALETTE.BLUE_GRAY._50,
  },
  receiptFooterPopover: {
    width: 245,
  },
  receiptFooterSelectText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: Colors.PALETTE.GRAY._700,
    textAlign: 'left',
    flex: 2,
  },
  receiptFooterSelectHeader: {
    fontSize: 15,
    color: Colors.PALETTE.GRAY._600,
    textAlign: 'left',
  },
  receiptFooterPopoverRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderStyle: 'solid',
    borderBottomWidth: 1,
    borderBottomColor: Colors.PALETTE.GRAY._500,
  },
  receiptHeaderIcon: {
    fontSize: 30,
    color: Colors.PALETTE.BLUE._700,
    marginHorizontal: 10,
  },
  receiptTypeSelectIconCheck: {
    color: Colors.PALETTE.GREEN._700,
    fontSize: 19,
  },
  viewRoot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  formContainer: {
    flex: 1,
    paddingVertical: 25,
    paddingHorizontal: 15,
  },
  formHeader: {
    fontSize: 13,
    fontWeight: 'bold',
    color: Colors.PALETTE.GRAY._800,
  },
  formHeaderContainer: {
    paddingBottom: 5,
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  receiptRoot: {
    flex: 1,
    backgroundColor: Colors.WHITE,
    paddingHorizontal: 10,
    borderBottomWidth: 2,
    borderBottomColor: Colors.PALETTE.GRAY._400,
    borderStyle: 'solid',
    shadowColor: Colors.PALETTE.GRAY._950,
    shadowOffset: {
      width: 5,
      height: 10,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2.5,
    elevation: 5,
  },
  receiptInfoRoot: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderStyle: 'solid',
    borderBottomColor: Colors.PALETTE.GRAY._400,
    borderBottomWidth: 1,
    paddingVertical: 5,
  },
  receiptInfoHeader: {
    textAlign: 'left',
    fontSize: 13,
    fontWeight: '600',
    color: Colors.PALETTE.GRAY._400,
  },
  receiptInfoContent: {
    fontSize: 15,
    fontWeight: '400',
    color: Colors.BLACK,
  },
  clientRoot: {
    width: '100%',
    backgroundColor: Colors.WHITE,
    minHeight: 110,
  },
  clientContentContainer: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    borderStyle: 'solid',
    borderBottomWidth: 1,
    borderBottomColor: Colors.PALETTE.GRAY._400,
    paddingVertical: 5,
  },
  clientNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 1,
  },
  clientNameLabel: {
    fontSize: 15,
    textAlign: 'left',
    fontWeight: '900',
  },
  clientDataContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 1,
  },
  clientPibAndMbText: {
    textAlign: 'right',
    color: Colors.PALETTE.GRAY._800,
    fontSize: 11,
  },
  clientAddressContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    flexWrap: 'wrap',
    paddingVertical: 1,
  },
  clientAddressText: {
    fontWeight: '500',
    fontSize: 10,
    color: Colors.PALETTE.GRAY._700,
  },
  clientRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
  },
  clientHeader: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._600,
  },
  optionalDataRoot: {
    borderStyle: 'solid',
    borderBottomColor: Colors.PALETTE.GRAY._400,
    borderBottomWidth: 1,
    paddingVertical: 5,
  },
  optionalDataRow: {
    flexDirection: 'row',
    width: '100%',
    paddingVertical: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optionalDataHeader: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._700,
  },
  optionalDataContent: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._950,
  },

  refundRoot: {
    borderStyle: 'solid',
    borderBottomColor: Colors.PALETTE.GRAY._400,
    borderBottomWidth: 1,
    paddingVertical: 5,
  },
  refundRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  refundHeader: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._700,
  },
  refundContent: {
    fontSize: 15,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._950,
  },
  advanceRoot: {
    borderStyle: 'solid',
    borderBottomColor: Colors.PALETTE.GRAY._400,
    borderBottomWidth: 1,
    paddingVertical: 5,
  },
  advanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  advanceHeader: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._800,
  },
  advanceContent: {
    fontSize: 13,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._800,
  },
  buttonRoot: {
    width: '100%',
    paddingVertical: 5,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginTop: 15
  },
  receiptHeaderInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptHeaderInfoText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: Colors.PALETTE.GRAY._700,
  },
  typeReceiptHeader: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._700,
  },
  typeReceiptContent: {
    fontSize: 14,
    fontWeight: '800',
    color: Colors.PALETTE.GRAY._950,
  },
  typeHeader: {
    flex: 1,
    textAlign: 'center',
    width: 100,
  },
});

export default style;
